### PR TITLE
New features: 'dragInitiated' argument and 'releaseTweese' option.

### PR DESCRIPTION
**Pull request by jonlinper**
**dragInitiated**

This adds a new callback argument to the 'change' event, that allows to know if the change has been caused by a dragging (mouse or touch) or not.

I've a Sly scroll as a background of another. So when moving it, background gets updated.
Animation is disabled when movement is a drag.

``` javascript
sly.on('change', function(eventName, dragInitiated) {
  background.slideTo((sly.pos.dest / sly.pos.end) * background.pos.end, dragInitiated);
});
```

**releaseTweese**

On the other hand, releaseTweese option allows to use a releaseSwing without tweese.
Tweese looks bad for my non-item Sly.

### CODE REVIEW

**Comment by darsain** [comment]
`change` event should be completely agnostic to dragging. Passing that argument there just doesn't make sense. Stuff like this should be inferred from Sly state properties.

One such property is an unfortunately undocumented `dragging` object, which has for you very useful properties `init`, and `released`.

So, inside the change event, check `sly.dragging.init` to get the same result.

**Comment by jonlinper** [comment]
Darsain,

Thanks for your message.
What about the `releaseTweese` option?

**Comment by darsain** [comment]
That's what `releaseSwing` option does.

**Comment by jonlinper** [comment]
It's not the same effect.

**Pull request closed without merging**
